### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaMolSim/Molly.jl#10]
I think registering the package in the JuliaMolSim registry at least could be helpful for the developing packages that need Molly for their tests (such as the upcoming ParticleAccelerations.jl).

I'm not sure how Pkg would deal with a package with the same UUID and name in both General and a private registry.

**Comment by jgreener64** [comment]
I'd rather register it in General directly. I see no harm in that as long as it is made clear in the readme/docs that people are getting a developing package, and any big announcement can wait until it's a bit more mature.

As I see it the only absolute blockers for a release are finishing the docs/docstrings and some more unit tests. Other low-hanging fruit like energy minimisation and more thermostats would be nice, but are not essential.

Over the weekend I'll have a look at getting it to a point where it's ready to tag v0.1 and register in General.

Does that sound okay?

**Comment by SebastianM-C** [comment]
That's great. It would make things much easier.

**Comment by jgreener64** [comment]
https://github.com/JuliaRegistries/General/pull/17220

**Comment by jgreener64** [comment]
That's now merged.
