### ISSUE TITLE
Molly needs a logo!

### ISSUE THREAD

**Issue by JaydevSR** [JuliaMolSim/Molly.jl#101]
As the title says, I think Molly needs a cool logo. Most Julia packages have made their logos using [Luxor.jl](https://github.com/JuliaGraphics/Luxor.jl) maybe one can be made for Molly as well (although I have no experience with Luxor).

**Comment by jgreener64** [comment]
Yes this sounds like a good idea. Something similar to the JuliaMolSim logo (https://github.com/JuliaMolSim) but referencing bonds/molecules/macromolecules would be cool.

**Comment by JaydevSR** [comment]
I experimented a bit with http://qutemol.sourceforge.net/, using this we have an illustration of 1cqh

<image width=400 src="https://user-images.githubusercontent.com/59474411/191063182-fc073a3b-61af-484f-b3c2-e933d7fbc552.png"></image>

@jgreener64  What do you think about using such figures for constructing the logo (in place of the classic julia dots).

**Comment by jgreener64** [comment]
That looks good, a related idea is to find a protein trimer and colour each chain so that it looks like the Julia logo.

Example PDB search: https://www.rcsb.org/search?request=%7B%22query%22%3A%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22text%22%2C%22parameters%22%3A%7B%22attribute%22%3A%22rcsb_struct_symmetry.oligomeric_state%22%2C%22operator%22%3A%22exact_match%22%2C%22negation%22%3Afalse%2C%22value%22%3A%22Homo%203-mer%22%7D%7D%5D%2C%22logical_operator%22%3A%22and%22%7D%5D%2C%22label%22%3A%22text%22%7D%5D%7D%2C%22return_type%22%3A%22entry%22%2C%22request_options%22%3A%7B%22paginate%22%3A%7B%22start%22%3A0%2C%22rows%22%3A25%7D%2C%22results_content_type%22%3A%5B%22experimental%22%5D%2C%22sort%22%3A%5B%7B%22sort_by%22%3A%22score%22%2C%22direction%22%3A%22desc%22%7D%5D%2C%22scoring_strategy%22%3A%22combined%22%7D%2C%22request_info%22%3A%7B%22query_id%22%3A%2286eb579095ba7acb02844c3721f1da5d%22%7D%7D

**Comment by JaydevSR** [comment]
Yes, this looks good, I will try and see if I can make a basic concept logo using these types of trimers.

**Comment by LegionAtol** [comment]
Hi @jgreener64 
I'm new to Molly.jl it seems like an interesting project and I'd like to contribute :)
I also like making nice presentations, logos etc... I thought I'd show you some logo proposals, I hope you like them

![Logo proposals](https://github.com/JuliaMolSim/Molly.jl/assets/118752873/ec86f081-17a4-4398-8c83-ea77fa0662e3)

**Comment by jgreener64** [comment]
These look great! Thanks for doing them. I particularly like the two larger molecules (2 and 4).

Would it be possible to do a variant of 4 with the 4 Julia logo colours, i.e. including the blue from the dot above the j as a fourth colour?

Does anyone else have any preferences from these?

**Comment by JaydevSR** [comment]
I also like the bigger ones, although I think it could also be great if some elements like protein chains, interactions etc. can be incorporated in the logo. 

I had some ideas earlier @LegionAtol, if you look at the link that Joe shared earlier with protein trimer complexes, then maybe that can be used with 3 julia colors, also the font can have a gradient in 4th julia color that is calculated using Lennard Jones potential formula? Just some random ideas we had but I didn't get the time to see through. Maybe you find some inspiration through these ✌️

**Comment by LegionAtol** [comment]
Certainly! I will work on the variations in these days @jgreener64 
I particularly like the first one and the fourth one as well
Thank you for the suggestions @JaydevSR, I will also take a look at the link ;)

**Comment by LegionAtol** [comment]
I made the variations, I hope they go well
If you have any other ideas/changes or reference images let me know
![logo](https://github.com/JuliaMolSim/Molly.jl/assets/118752873/f2624cba-b7be-4be5-aeb6-2efaab068f2e)

**Comment by jgreener64** [comment]
Thanks for these. I do like the fourth one in the last set (ball and stick). Would you be able to do a variant with a slightly more horizontal molecule, and a variant with a different font? Also, just checking that the colours are the exact RGB match from the Julia logo?

I would be tempted to go with a variant of that as the logo, but anyone else with thoughts should feel free to add them.

**Comment by JaydevSR** [comment]
@LegionAtol thanks. I agree as well that the 4th one looks the best. For the fonts, if you try a monospace variant, it would be worth trying the juliamono font https://juliamono.netlify.app/, also I have a suggestion of a variant where a dashed bond can be mixed in somewhere to show a different kind of interaction (like a weak interaction between two molecules), not sure how good it'll look but could be interesting.

**Comment by LegionAtol** [comment]
thanks for the suggestions
I corrected the colors, now they are more accurate (I converted from RGB to HEX). 
These are the variations, I tilted the molecule a little more horizontally and tried some fonts, the one at the bottom right is the JuliaMono font.
On two molecules, I added the dashed bond, but if needed, it can be removed. Let me know if it's okay or if we need to make further changes. (If we choose one in the end, I can redo it a bit better and also at a higher resolution)
![logo4](https://github.com/JuliaMolSim/Molly.jl/assets/118752873/cb725bd7-87a2-4e13-b04f-8f942c025e28)

**Comment by jgreener64** [comment]
These look great. My favourite is row 3 column 2. If you could redo that one without the dashed bond and at high resolution then maybe we say that is the logo.

We would probably want a SVG and a PNG version, without background. If you could make a PR to put these in `docs/src/images` that would be great.
