### ISSUE TITLE
Symbol missing error when running documentation code

### ISSUE THREAD

**Issue by ejmeitz** [JuliaMolSim/Molly.jl#106]
Hello,

I ran the code at the beginning of the [docs](https://juliamolsim.github.io/Molly.jl/dev/docs/#Simulation-basics). I get a bounds error: 
`BoundsError: attempt to access 0-element Vector{Any} at index [1]`
because at line 676 of types.jl the system tries to assign each atom a symbol:
`AtomsBase.atomic_symbol(s::Union{System, ReplicaSystem}, i::Integer) = Symbol(s.atoms_data[i].element)`
However, atom_data is not a required parameter in the System struct so something seems wrong here to me.

Am I doing something wrong? The entire code is below:

````
using Molly

n_atoms = 100
atom_mass = 10.0u"u"
atoms = [Atom(mass=atom_mass, σ=0.3u"nm", ϵ=0.2u"kJ * mol^-1") for i in 1:n_atoms]

boundary = CubicBoundary(2.0u"nm", 2.0u"nm", 2.0u"nm") # Periodic boundary conditions
coords = place_atoms(n_atoms, boundary; min_dist=0.3u"nm") # Random placement without clashing

temp = 100.0u"K"
velocities = [velocity(atom_mass, temp) for i in 1:n_atoms]

pairwise_inters = (LennardJones(),) # Don't forget the trailing comma!

sys = System(
    atoms=atoms,
    pairwise_inters=pairwise_inters,
    coords=coords,
    velocities=velocities,
    boundary=boundary,
    loggers=(
        temp=TemperatureLogger(10),
        coords=CoordinateLogger(10),
    ),
)

simulator = VelocityVerlet(
    dt=0.002u"ps",
    coupling=AndersenThermostat(temp, 1.0u"ps"),
)

simulate!(sys, simulator, 1_000)
````

**Comment by jgreener64** [comment]
This is an error introduced by a recent update to AtomsBase.jl, thanks for reporting.

I just pushed a fixed and tagged v0.14.1, once that filters through this should be fixed.
