### ISSUE TITLE
Molly Feature Parity List

### ISSUE THREAD

**Issue by ejmeitz** [JuliaMolSim/Molly.jl#108]
Any interest in making a LAMMPS feature parity list similar to what Flux [has ](https://github.com/FluxML/Flux.jl/issues/1431)with PyTorch? Or honestly just an updated list of missing features I think would be good. I definitely have my own ideas, and I think it would be nice to have a publicly available list of features Molly has and does not have. Maybe separate it into two lists: one to match parity with LAMMPS and another that is features only in Molly.

**Comment by jgreener64** [comment]
The lists on the readme are intended to be that, feel free to add or update as appropriate.
