### ISSUE TITLE
Unit conversion for general interactions

### ISSUE THREAD

**Issue by swyant** [JuliaMolSim/Molly.jl#121]
Hello, 

I'm currently working on improving the interoperability between [InteratomicPotentials.jl](https://github.com/cesmix-mit/InteratomicPotentials.jl) and Molly. I have a mostly working prototype (based off of some past work) using Lennard-Jones as an example that can be seen  [here](https://github.com/swyant/exploratory_julia_sessions/blob/2da6668789efdcdd3907f7ae549397081c2a3c21/interpot_comparisons/lj/no_pluto/fcc_argon_lj_via_molly.jl). The near-term goal is to get various machine-learned interatomic potentials working as well.

The primary issue is that the forces outputted from InteratomicPotentials.jl are in atomic units (i.e. Hartree/Bohr), but I typically use units of eV/Å.  However, if I set my ForceUnits=u"eV/Å" in my Molly system, it appears that no unit checking occurs (for the general interactions), the units are stripped, and the user-specified units are incorrectly appended, with no unit conversion. While I can manage the units on my end, I think it would be safer/more reliable if these units were converted appropriately within Molly.

I've discussed this issue a bit with @leios already, but any additional help is appreciated! Thank you!

**Comment by jgreener64** [comment]
Looks cool, and I am excited about the machine learning potentials.

You are correct that currently forces are stripped without checking, which is a problem: https://github.com/JuliaMolSim/Molly.jl/blob/588e46372fcebbb1d263907812e5ad4e49274a3f/src/force.jl#L298-L301

This is fixed on the work in progress `kernels` branch though:

https://github.com/JuliaMolSim/Molly.jl/blob/7ea9481346aea78ca933401281219644fd4d62c0/src/force.jl#L167-L169

Hopefully that branch should be merged soon, it contains many other improvements too. I just need to clean up the docs a bit and wait for a new Enzyme release to be tagged.

**Comment by jgreener64** [comment]
It was merged a few days ago so you should be good to go.

**Comment by jgreener64** [comment]
I should add that currently the units returned by the interaction should be the same as the system force units, being convertible to them isn't sufficient. This is because there was a slight performance hit of allowing the conversion, which may be fixed in future.

**Comment by swyant** [comment]
Ah, good to know! Thanks
