### ISSUE TITLE
AtomsBase not properly implemented

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/Molly.jl#128]
Just a remark that I noted that the latest AtomsBase interface (0.3) is not properly supported by Molly. E.g. `hasatomkey(sys, :testkey)` on a Molly system gives an infinite stacktrace.

We should take a look at this and integrate with [`AtomsBaseTesting`](https://juliamolsim.github.io/AtomsBase.jl/stable/testing/) in the CI of Molly.

**Comment by jgreener64** [comment]
Thanks for pointing this out Michael - we'll add AtomsBaseTesting and fix any issues.

**Comment by jgreener64** [comment]
Should be fixed by #131.
