### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by HLinde** [JuliaMolSim/Molly.jl#146]
I am using Molly.jl for my doctoral project and want to add a citation.
Do you have a preferred way of citation?
Have you considered adding a "CITATION" file?
(https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
Thanks a lot!

**Comment by HLinde** [comment]
Thanks, I will do it like that :)

I found the package to be very accessible in contrast to other MD packages I found. And it also helped me a lot, that it is quite simple to further extend it with other interactions.
I will send you a link once the thesis is published.

**Comment by jgreener64** [comment]
See https://github.com/JuliaMolSim/Molly.jl#citation and https://github.com/JuliaMolSim/Molly.jl/blob/master/CITATION.bib.

**Comment by HLinde** [comment]
I just remembered you were interested to see the work. My thesis is now published for some time :)
https://doi.org/10.11588/heidok.00033965
Thanks again!

**Comment by jgreener64** [comment]
Thanks, looks interesting.
