### ISSUE TITLE
Progress logging suggestions

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaMolSim/Molly.jl#18]
I was thinking that it may be useful to consider an option to toggle progress monitoring, as during benchmarks it may not always be useful.
An other thing that may improve user experience would be to switch to [ProgressLogging.jl](https://github.com/JunoLab/ProgressLogging.jl/) as this could show progress in IDEs (such as Juno) and also the terminal.

**Comment by jgreener64** [comment]
Sounds like a good idea, I usually disable the progress bar for benchmarking but it could be a keyword argument to `simulate!`.

**Comment by jgreener64** [comment]
The progress bar has been removed.
