### ISSUE TITLE
Request: clarifying units that Molly uses

### ISSUE THREAD

**Issue by ehgus** [JuliaMolSim/Molly.jl#39]
I'm excited that Molecular dynamics is implemented in julia so I'd like to test it!
But I struggled with finding inplicit units that Molly uses and I found them in GROMACS website.

I know Molly targets GROMACS file formats and units, but I don't want to find Molly documents in GROMACS website.
Also clear unit descriptiion would be helpful when non-GROMACS users (actually it's me!) try to convert their non-GROMACS file formats suitable for Molly.
Or redirecting GROMACS unit description page will save user's time
https://manual.gromacs.org/documentation/current/reference-manual/topologies/topology-file-formats.html

Thank you for your effort.

**Comment by jgreener64** [comment]
Yes work is ongoing on the `unitful` branch for this. The idea is to have units for every quantity specified explicitly, and therefore to allow any self-consistent set of units to be used.

Just trying to iron out some API issues and performance regressions on that branch at the moment.

See also https://github.com/JuliaMolSim/Molly.jl/issues/34.

**Comment by jgreener64** [comment]
As of v0.4.0 you can use Unitful.jl units across the package. See the docs for more.
