### ISSUE TITLE
Inconsistency with AtomsBase interface

### ISSUE THREAD

**Issue by jrdegreeff** [JuliaMolSim/Molly.jl#55]
There are a couple things that the `System` implementation is missing for it to be fully interchangable with other `AtomsBase` implementations.

1. `atomic_symbol(::System, ::Integer)` is not implemented
2. `getindex(::System, ::Integer)` returns a struct with insufficient fields to be useful in the way that iterating over other `AbstractSystem` is useful. Specifically this is a problem in my `Atomistic` and `DFTK` integration code where I have to have a special case for a `System` versus an `AbstractSystem`. This could be resolved simply by having `getindex` return an [`AtomView`](https://github.com/JuliaMolSim/AtomsBase.jl/blob/master/src/atomview.jl) (though any current usage of `getindex` would have to be modified).

**Comment by jrdegreeff** [comment]
Looking at the codecov report, the current `getindex` implementation is not used in any of the tests, so this might be an even easier change than I was expecting. I can put together a quick prototype PR if you'd like.

**Comment by jgreener64** [comment]
If you have the time that would be great. I guess `atomic_symbol` can use the `element` field in `atoms_data`.

**Comment by jrdegreeff** [comment]
I've had a super busy week, but sitting down now to do this. I'll open a PR momentarily.
