### ISSUE TITLE
FENE bond and Cosine angle potential

### ISSUE THREAD

**Issue by ehsanirani** [JuliaMolSim/Molly.jl#73]
I have been watching Molly.jl and its fast development for a while and really like it. Recently decided to use it for my new research project and first test results are promising. See a simple model of molecular motor walking along a polymer:

https://nxcloud.omid.land/s/czXWqnM8KZFFxDK

However Molly.jl still lacks some essential features of a proper MD package, like [FENE bonds](https://en.wikipedia.org/wiki/FENE) and cosine angles. I already implemented them for my own research, if nobody else is working on those currently, I can do some code styling and make a pull request to add them to Molly.

**Comment by jgreener64** [comment]
That looks great! It's exciting to see other people use the software.

PRs to add those features would be very welcome, I don't think they are being worked on currently.

If you would like to add a minimal code example or link to a paper on the examples docs page that would also be very welcome.

**Comment by ehsanirani** [comment]
I just added a pull request #74 . Hope it is useful.

**Comment by jgreener64** [comment]
Closed via #74.
