### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by chemicalfiend** [JuliaMolSim/Molly.jl#92]
I'm not really an expert with how Markdown works or how it parses links but a lot of links in the docs seem to head to `https://github.com/JuliaMolSim/Molly.jl/blob/master/docs/src/@ref` , when clicking on them it leads to the 404 GitHub page. The links that head to Wikipedia and stuff obviously work but everything that points back to something else in Molly.jl docs seems broken. I don't really know what `@ref` is supposed to do so I decided to flag an issue instead of fixing it.

![Sun Aug 21 09:14:38 AM IST 2022](https://user-images.githubusercontent.com/78299309/185774510-3efa9898-5a47-4417-a4ba-2095294c60dd.png)

**Comment by jgreener64** [comment]
That is the case when viewing the raw markdown. However Documenter.jl is used to build the docs during CI and replaces these `@ref` links with proper links to the docstrings on the API page. These can be see in the [deployed docs](https://juliamolsim.github.io/Molly.jl/dev/docs). That should be how most users view the docs - let me know if you see any broken links there.

**Comment by chemicalfiend** [comment]
Yep, it's fine in the website of the docs, just messes up when viewing on GitHub. I'll close the issue then. Thanks for clarifying.
